services:
  app:
    build: .
    container_name: resume_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: postgres:16
    container_name: resume_db
    restart: always
    environment:
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: resume_pass
      POSTGRES_DB: resume_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

  nginx:
    image: nginx:alpine
    container_name: resume_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app_net

  certbot:
    image: certbot/certbot
    container_name: resume_certbot
    command: ["sh", "-c", "trap : TERM; while :; do sleep 3600; done"]
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot

volumes:
  db_data:
  certbot-etc:
  certbot-var:

networks:
  app_net: