# .github/workflows/deploy.yml
name: Deploy via SSH (no registry)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Если папки проекта ещё нет — клонируем
            if [ ! -d "/home/${{ secrets.SERVER_USER }}/IamDRG/.git" ]; then
              git clone git@github.com:IDRGI-hub/IamDRG.git /home/${{ secrets.SERVER_USER }}/IamDRG
            fi

            cd /home/${{ secrets.SERVER_USER }}/IamDRG

            # Обновляем код
            git pull origin main

            # Собираем и перезапускаем стек
            docker-compose up -d --build
