# .github/workflows/deploy.yml
name: Deploy via SSH (no registry)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Если папки проекта ещё нет — клонируем
            if [ ! -d "/home/${{ secrets.SERVER_USER }}/IamDRG/.git" ]; then
              git clone git@github.com:IDRGI-hub/IamDRG.git /home/${{ secrets.SERVER_USER }}/IamDRG
            fi

            cd /home/${{ secrets.SERVER_USER }}/IamDRG

            # Обновляем код
            git pull origin main

            # Создаем .env файл из secrets
            cat > .env << EOF
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            APP_SECRET_KEY=${{ secrets.APP_SECRET_KEY }}
            APP_DEBUG=False
            APP_HOST=0.0.0.0
            APP_PORT=8000
            DOMAIN_NAME=${{ secrets.DOMAIN_NAME }}
            ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
            EOF

            # Собираем и перезапускаем стек
            docker-compose down
            docker-compose up -d --build
